DIR_NPUT = ../input

DIR_TASK1 = ./task_1
DIR_TASK2 = ./task_2
DIR_SRC = ./src

all:
	$(MAKE) -C $(DIR_NPUT)
	$(MAKE) -C $(DIR_TASK1)
	$(MAKE) -C $(DIR_TASK2)
	$(MAKE) -C $(DIR_SRC)

clean:
	$(MAKE) -C $(DIR_TASK1) clean
	$(MAKE) -C $(DIR_TASK2) clean
	$(MAKE) -C $(DIR_SRC) clean